import type { Education, Ethnicity, KSResult, MetroAcsStats, UserProfile } from '../types';
import { clamp, normalCdf } from '../lib/math';

const educationOrdinal: Record<Education, number> = { high_school_or_less: 0.2, some_college: 0.45, associates: 0.55, bachelors: 0.8, graduate: 1.0 };
const crossEthnicWeights: Record<Ethnicity, Record<Ethnicity, number>> = {
  white: { white: 1.0, black: 0.22, hispanic: 0.28, asian: 0.18, other: 0.14 },
  black: { white: 0.26, black: 1.0, hispanic: 0.22, asian: 0.12, other: 0.15 },
  hispanic: { white: 0.24, black: 0.18, hispanic: 1.0, asian: 0.12, other: 0.15 },
  asian: { white: 0.32, black: 0.14, hispanic: 0.16, asian: 1.0, other: 0.12 },
  other: { white: 0.18, black: 0.14, hispanic: 0.18, asian: 0.14, other: 1.0 },
};
const totalHeightInches = (p: UserProfile) => p.heightFeet * 12 + p.heightInchesRemainder;
function getHeightFactor(p: UserProfile): number { const i=totalHeightInches(p); if (p.gender==='male'){ if(i>=74)return 0.08; if(i>=72)return 0.05; if(i>=70)return 0; if(i>=68)return -0.05; if(i>=66)return -0.1; return -0.16;} if(i<69)return 0; if(i<=71)return -0.03; return -0.08; }
function getBuildFactor(p: UserProfile): number { const i=totalHeightInches(p); const bmi=(p.weightLbs/(i*i))*703; if(p.gender==='male'){ if(bmi>=22&&bmi<=29)return 0; if((bmi>=20&&bmi<22)||(bmi>29&&bmi<=32))return -0.03; if((bmi>=18&&bmi<20)||(bmi>32&&bmi<=35))return -0.08; return -0.14; } if(bmi>=20&&bmi<=27)return 0; if((bmi>=18&&bmi<20)||(bmi>27&&bmi<=30))return -0.03; if((bmi>=17&&bmi<18)||(bmi>30&&bmi<=34))return -0.08; return -0.14; }
function getAgeFactor(p: UserProfile): number { const a=p.age; if(p.gender==='male'){ if(a<25)return -0.2; if(a<=34)return 0.05; if(a<=49)return 0.12; if(a<=59)return 0.06; if(a<=69)return -0.08; return -0.18;} if(a<25)return 0.05; if(a<=34)return 0.14; if(a<=44)return 0.06; if(a<=54)return -0.05; if(a<=64)return -0.16; return -0.25; }
function getChildrenFactor(p: UserProfile): number { const c=Math.min(p.childrenCount,4); return p.gender==='male' ? [-0,-0.05,-0.09,-0.13,-0.16][c] : [-0,-0.07,-0.12,-0.17,-0.21][c]; }
function getMarriageHistoryFactor(p: UserProfile): number { if(p.priorMarriages<=0)return 0; if(p.priorMarriages===1)return -0.05; if(p.priorMarriages===2)return -0.11; return -0.18; }
function preferredPartnerAgeRange(p: UserProfile): [number,number] { return p.gender==='male' ? [Math.max(18,p.age-12), Math.max(18,p.age-2)] : [Math.max(18,p.age-2), p.age+8]; }
function ageWeight(p: UserProfile, partnerMidAge: number): number { const preferredAge=p.gender==='male' ? p.age-4 : p.age+2; const diff=Math.abs(partnerMidAge-preferredAge); if(diff<=2)return 1; if(diff<=5)return 0.8; if(diff<=8)return 0.55; if(diff<=12)return 0.3; return 0.1; }
function incomeFactor(p: UserProfile, m: MetroAcsStats): number { return clamp(Math.log(Math.max(0.2,p.income/Math.max(1,m.medianHouseholdIncome))), -1, 1); }
function educationFactor(p: UserProfile, m: MetroAcsStats): number { const own=educationOrdinal[p.education]; const metroWeighted=m.educationShares.high_school_or_less*educationOrdinal.high_school_or_less+m.educationShares.some_college*educationOrdinal.some_college+m.educationShares.associates*educationOrdinal.associates+m.educationShares.bachelors*educationOrdinal.bachelors+m.educationShares.graduate*educationOrdinal.graduate; return clamp(own-metroWeighted,-0.5,0.5); }
function computeDemandPool(p: UserProfile, m: MetroAcsStats): number { const [minAge,maxAge]=preferredPartnerAgeRange(p); const ethWeights=crossEthnicWeights[p.ethnicity]; const eduBoost=p.gender==='male' ? 0.7+(educationOrdinal[p.education]*0.3) : 0.75+(educationOrdinal[p.education]*0.2); const incBoost=p.gender==='male' ? 0.75+(clamp(p.income/Math.max(1,m.medianHouseholdIncome),0.25,2)*0.15) : 0.82+(clamp(p.income/Math.max(1,m.medianHouseholdIncome),0.25,2)*0.08); const key = p.gender==='male' ? 'femaleSinglePopulation' : 'maleSinglePopulation'; let pool=0; for(const band of m.ageBands){ if(band.midAge<minAge||band.midAge>maxAge) continue; const available=band[key as 'femaleSinglePopulation']; const ageCompat=ageWeight(p, band.midAge); const ethBlend=m.ethnicityShares.white*ethWeights.white+m.ethnicityShares.black*ethWeights.black+m.ethnicityShares.hispanic*ethWeights.hispanic+m.ethnicityShares.asian*ethWeights.asian+m.ethnicityShares.other*ethWeights.other; pool += available*ageCompat*ethBlend*eduBoost*incBoost; } return Math.max(pool,1); }
function computeCompetitionPool(p: UserProfile, m: MetroAcsStats): number { const band=m.ageBands.find(b=>Math.abs(b.midAge-p.age)<=3) ?? m.ageBands[0]; const sameSex=p.gender==='male' ? band.maleSinglePopulation : band.femaleSinglePopulation; const ethnicityShare=m.ethnicityShares[p.ethnicity]; const educationShare=p.education==='graduate' ? m.educationShares.graduate : p.education==='bachelors' ? m.educationShares.bachelors+m.educationShares.graduate : p.education==='associates' ? m.educationShares.associates : p.education==='some_college' ? m.educationShares.some_college : m.educationShares.high_school_or_less; const incomeSimilarity=clamp(p.income/Math.max(1,m.medianHouseholdIncome),0.4,2.5); const familyPenalty=1-Math.min(0.25,p.childrenCount*0.04+p.priorMarriages*0.03); return Math.max(sameSex*Math.max(ethnicityShare,0.04)*Math.max(educationShare,0.08)*(0.55+incomeSimilarity*0.22)*familyPenalty,1); }
function interactionFactor(p: UserProfile, m: MetroAcsStats, inc: number, edu: number): number { const band=m.ageBands.find(b=>Math.abs(b.midAge-p.age)<=3) ?? m.ageBands[0]; const sexRatio=band.femalePopulation/Math.max(band.malePopulation,1); const ageAdv=p.gender==='male' ? sexRatio-1 : 1-sexRatio; const highEduScarcity=1-(m.educationShares.bachelors+m.educationShares.graduate); const ethnicityDemand=crossEthnicWeights[p.ethnicity][p.ethnicity]*m.ethnicityShares[p.ethnicity]; return (0.1*inc*highEduScarcity)+(0.08*edu*highEduScarcity)+(0.12*ageAdv)+(0.04*ethnicityDemand); }
export function calculateKS(p: UserProfile, m: MetroAcsStats): KSResult { const inc=incomeFactor(p,m), edu=educationFactor(p,m), age=getAgeFactor(p), height=getHeightFactor(p), build=getBuildFactor(p), children=getChildrenFactor(p), marriages=getMarriageHistoryFactor(p); const profileFactor=0.28*inc+0.14*edu+0.16*age+0.08*height+0.06*build+0.12*children+0.08*marriages; const demandPool=computeDemandPool(p,m); const competitionPool=computeCompetitionPool(p,m); const interaction=interactionFactor(p,m,inc,edu); const ksRaw=Math.log(demandPool/competitionPool)+profileFactor+interaction; const scoreMean=3.2, scoreStdDev=0.85; const zScore=(ksRaw-scoreMean)/scoreStdDev; const percentile=clamp(normalCdf(zScore),0.01,0.99); const ksScore=Math.round(percentile*100); const drivers=[['Income relative to local median',0.28*inc],['Education relative to local mix',0.14*edu],['Age position in this market',0.16*age],['Height effect',0.08*height],['Build effect',0.06*build],['Children effect',0.12*children],['Prior marriage effect',0.08*marriages],['Metro-specific scarcity effects',interaction]].sort((a,b)=>Math.abs(b[1] as number)-Math.abs(a[1] as number)).slice(0,5).map(([label,impact])=>({label: label as string, direction: ((impact as number)>=0 ? 'positive' : 'negative') as 'positive' | 'negative', impact: Math.abs(impact as number)})); const [ageTargetMin,ageTargetMax]=preferredPartnerAgeRange(p); return { metroId:m.metroId, metroLabel:m.metroLabel, ksRaw, ksScore, percentile, demandPool, competitionPool, scoreMean, scoreStdDev, zScore, drivers, summary:{ ageTargetMin, ageTargetMax, metroMedianIncome:m.medianHouseholdIncome } }; }
